### ISSUE TITLE
LoadError: no such file to load -- ffi

### ISSUE THREAD

**Issue by telephono** [thomasjachmann/launchpad#1]
In a clean gem environment with only launchpad and portmidi gems installed

``` ruby
require 'launchpad'
```

fails with

```
LoadError: no such file to load -- ffi
```

I'm not sure if its a launchpad or portmidi requirement, but maybe you should add it to the gem requirements...

**Comment by thomasjachmann** [comment]
It actually is a portmidi requirement. The portmidi gem is a wrapper for ffi, so actually portmidi should have it as a runtime requirement, but Jan deleted it because of JRuby incompatibilities. I can't add ffi to launchpad's dependencies since launchpad doesn't have a direct dependency to ffi in itself. Feel free to open an issue on portmidi's issue tracker.
