### ISSUE TITLE
Error using library

### ISSUE THREAD

**Issue by ghost** [thomasjachmann/launchpad#5]
MIDI device  doesn't exist (Launchpad::NoSuchDeviceError)

I successfully installed portmidi, the portmidi gem and launchpad then tried one of the samples and got the previous error. Anyone ran into this before?

**Comment by ghost** [comment]
Oh and I have my launchpad mini plugged in obviously. Currently working with a JS library but Id rather ruby. Now I have it working with the go library too that uses portmidi. Is this compatible with the launchpad mini?

**Comment by thomasjachmann** [comment]
Sorry it has taken me so long to notice there's a new issue.

Your Launchpad Mini's MIDI device probably has a different name than the standard Launchpad. In the examples, the `Launchpad::Device` and `Launchpad::Interaction` objects are instantiated with the defaults so they're trying to connect to a MIDI device named "Launchpad". Check your computer's MIDI configuration for the name used, then you can modify the examples and pass `:device_name => 'the name of your device'` to the constructors.

Due to lack of such a device, I don't know if the Launchpad Mini is compatible. There's no Programmer's Reference on Novation's website for the Mini, but give it a try and please let me know if everything's working.

**Comment by ghost** [comment]
I will give it a try this weekend. Thanks for getting back to me on this.

**Comment by KyeRussell** [comment]
Hi, Just FYI, the device's name is `Launchpad Mini`.

**Comment by movitto** [comment]
Just submitted PR #7 which should resolve this issue

**Comment by movitto** [comment]
And yes, everything works with the midi after that 👍
